Import version 0.99+dfsg-1
Imported using git-dsc-commit.

diff --git a/debian/clamav-freshclam.postinst.in b/debian/clamav-freshclam.postinst.in
--- a/debian/clamav-freshclam.postinst.in
+++ b/debian/clamav-freshclam.postinst.in
@@ -30,7 +30,7 @@ set -e
 
 FRESHCLAMCONFFILE=/etc/clamav/freshclam.conf
 FRESHCLAMLOGFILE=/var/log/clamav/freshclam.log
-DEBCONFILE=/var/lib/clamav/freshclam.conf
+DEBCONFFILE=/var/lib/clamav/freshclam.conf
 LOGROTFILE=/etc/logrotate.d/clamav-freshclam
 DEBROTFILE=/var/lib/clamav/clamav-freshclam
 
@@ -142,9 +142,9 @@ case "$1" in
       echo "     create 640  $User adm" >> $DEBROTFILE
       echo "     postrotate" >> $DEBROTFILE
       echo "     if [ -d /run/systemd/system ]; then" >> $DEBROTFILE
-      echo "         systemctl -q is-active clamav-freshclam && systemctl kill --signal=SIGHUP clamav-freshclam" >> $DEBROTFILE
+      echo "         systemctl -q is-active clamav-freshclam && systemctl kill --signal=SIGHUP clamav-freshclam || true" >> $DEBROTFILE
       echo "     else" >> $DEBROTFILE
-      echo "         /etc/init.d/clamav-freshclam reload-log > /dev/null" >> $DEBROTFILE
+      echo "         /etc/init.d/clamav-freshclam reload-log > /dev/null || true" >> $DEBROTFILE
       echo "     fi" >> $DEBROTFILE
       echo "     endscript" >> $DEBROTFILE
       echo "     }" >> $DEBROTFILE
@@ -216,7 +216,7 @@ case "$1" in
   [ -z "$TestDatabases" ] && TestDatabases=yes
 
   # Generate config file
-  cat >> $DEBCONFILE << EOF
+  cat >> $DEBCONFFILE << EOF
 # Automatically created by the clamav-freshclam postinst
 # Comments will get lost when you reconfigure the clamav-freshclam package
 
@@ -244,70 +244,70 @@ Bytecode $Bytecode
 EOF
 
   if [ -n "$notify" ] ;then
-    echo "NotifyClamd $notify" >> $DEBCONFILE
+    echo "NotifyClamd $notify" >> $DEBCONFFILE
   fi
 
   if [ "$runas" != "cron" ] || [ "$runas" != "manual" ]; then
     if [ -n "$checks" ] && [ "$checks" != "true" ]; then
-      echo "# Check for new database $checks times a day" >> $DEBCONFILE
-      echo "Checks $checks" >> $DEBCONFILE
+      echo "# Check for new database $checks times a day" >> $DEBCONFFILE
+      echo "Checks $checks" >> $DEBCONFFILE
     fi
   fi
   if [ -n "$mirrors" ]; then
     for i in $mirrors; do
-      echo "DatabaseMirror $i" >> $DEBCONFILE
+      echo "DatabaseMirror $i" >> $DEBCONFFILE
     done
   fi
   # the first mirror is managed via debconf (and might have been changed)
   DatabaseMirror="`echo $DatabaseMirror | sed 's/^[[:space:]]*[^[:space:]]\+[[:space:]]\*//'`"
   DatabaseMirror="$DatabaseMirror database.clamav.net"
   for m in $DatabaseMirror; do
-    grep -q "$m" "$DEBCONFILE" || echo "DatabaseMirror $m" >> $DEBCONFILE
+    grep -q "$m" "$DEBCONFFILE" || echo "DatabaseMirror $m" >> $DEBCONFFILE
   done
 
   if [ -n "$phost" ]; then
-    echo "# Proxy: $fullurl" >> $DEBCONFILE
-    echo "HTTPProxyServer $phost" >> $DEBCONFILE
+    echo "# Proxy: $fullurl" >> $DEBCONFFILE
+    echo "HTTPProxyServer $phost" >> $DEBCONFFILE
     if [ -n "$pport" ]; then
-      echo "HTTPProxyPort $pport" >> $DEBCONFILE
+      echo "HTTPProxyPort $pport" >> $DEBCONFFILE
     fi
   fi
   if [ -n "$puser" ] && [ -n "$ppass" ]; then
-    echo "# Proxy authentication: $fulluser" >> $DEBCONFILE
-    echo "HTTPProxyUsername $puser" >> $DEBCONFILE
-    echo "HTTPProxyPassword $ppass" >> $DEBCONFILE
+    echo "# Proxy authentication: $fulluser" >> $DEBCONFFILE
+    echo "HTTPProxyUsername $puser" >> $DEBCONFFILE
+    echo "HTTPProxyPassword $ppass" >> $DEBCONFFILE
   fi
 
-  if `dpkg --compare-versions "$2" lt 0.98.5+dfsg-4~`; then
+  if `dpkg --compare-versions "$2" lt 0.98.7+dfsg-2~`; then
     # Remove the PidFile variable from the configuration, if it is the previous default value.
     if [ "$PidFile" = "/var/run/clamav/freshclam.pid" ]; then
       PidFile=''
     fi
   fi
-  [ -n "$PidFile" ] && echo "PidFile $PidFile" >> $DEBCONFILE
-  [ -n "$HTTPUserAgent" ] && echo "HTTPUserAgent $HTTPUserAgent" >> $DEBCONFILE
-  [ -n "$OnOutdatedExecute" ] && echo "OnOutdatedExecute $OnOutdatedExecute" >> $DEBCONFILE
-  [ -n "$OnUpdateExecute" ] && echo "OnUpdateExecute $OnUpdateExecute" >> $DEBCONFILE
-  [ -n "$OnErrorExecute" ] && echo "OnErrorExecute $OnErrorExecute" >> $DEBCONFILE
-  [ -n "$LocalIPAddress" ] && echo "LocalIPAddress $LocalIPAddress" >> $DEBCONFILE
-  [ -n "$SubmitDetectionStats" ] && echo "SubmitDetectionStats $SubmitDetectionStats" >> $DEBCONFILE
-  [ -n "$DetectionStatsCountry" ] && echo "DetectionStatsCountry $DetectionStatsCountry" >> $DEBCONFILE
-  [ -n "$DetectionStatsHostID" ] && echo "DetectionStatsHostID $DetectionStatsHostID" >> $DEBCONFILE
-  [ -n "$PrivateMirror" ] && echo "PrivateMirror $PrivateMirror" >> $DEBCONFILE
+  [ -n "$PidFile" ] && echo "PidFile $PidFile" >> $DEBCONFFILE
+  [ -n "$HTTPUserAgent" ] && echo "HTTPUserAgent $HTTPUserAgent" >> $DEBCONFFILE
+  [ -n "$OnOutdatedExecute" ] && echo "OnOutdatedExecute $OnOutdatedExecute" >> $DEBCONFFILE
+  [ -n "$OnUpdateExecute" ] && echo "OnUpdateExecute $OnUpdateExecute" >> $DEBCONFFILE
+  [ -n "$OnErrorExecute" ] && echo "OnErrorExecute $OnErrorExecute" >> $DEBCONFFILE
+  [ -n "$LocalIPAddress" ] && echo "LocalIPAddress $LocalIPAddress" >> $DEBCONFFILE
+  [ -n "$SubmitDetectionStats" ] && echo "SubmitDetectionStats $SubmitDetectionStats" >> $DEBCONFFILE
+  [ -n "$DetectionStatsCountry" ] && echo "DetectionStatsCountry $DetectionStatsCountry" >> $DEBCONFFILE
+  [ -n "$DetectionStatsHostID" ] && echo "DetectionStatsHostID $DetectionStatsHostID" >> $DEBCONFFILE
+  [ -n "$PrivateMirror" ] && echo "PrivateMirror $PrivateMirror" >> $DEBCONFFILE
   if [ -n "$DatabaseCustomURL" ]; then
     for i in $DatabaseCustomURL; do
-      echo "DatabaseCustomURL $i" >> $DEBCONFILE
+      echo "DatabaseCustomURL $i" >> $DEBCONFFILE
     done
   fi
   if [ -n "$ExtraDatabase" ]; then
     for i in $ExtraDatabase; do
-      echo "ExtraDatabase $i" >> $DEBCONFILE
+      echo "ExtraDatabase $i" >> $DEBCONFFILE
     done
   fi
   
   ucf_cleanup "$FRESHCLAMCONFFILE"
-  ucf_upgrade_check "$FRESHCLAMCONFFILE" "$DEBCONFILE" /var/lib/ucf/cache/:etc:clamav:freshclam.conf
-  rm -f "$DEBCONFILE"
+  ucf_upgrade_check "$FRESHCLAMCONFFILE" "$DEBCONFFILE" /var/lib/ucf/cache/:etc:clamav:freshclam.conf
+  rm -f "$DEBCONFFILE"
 
   db_stop || true
   
@@ -341,7 +341,7 @@ EOF
     if [ -x "/etc/init.d/clamav-freshclam" ]; then
       update-rc.d clamav-freshclam defaults >/dev/null
     fi
-    if [ -x /usr/sbin/invoke-rc.d ]; then
+    if pathfind invoke-rc.d; then
       invoke-rc.d clamav-freshclam start
     else
       /etc/init.d/clamav-freshclam start
@@ -349,7 +349,7 @@ EOF
   elif [ "$runas" = 'ifup.d' ]; then
     for intrface in $iface; do
       if route | grep -q "$intrface"; then
-        if [ -x /usr/sbin/invoke-rc.d ]; then
+        if pathfind invoke-rc.d; then
           IFACE="$intrface" invoke-rc.d clamav-freshclam start || true
         else
           IFACE="$intrface" /etc/init.d/clamav-freshclam start || true
@@ -360,7 +360,7 @@ EOF
     update-rc.d -f clamav-freshclam remove > /dev/null 2>&1
   else
     echo "Starting database update: "
-    if [ -x /usr/sbin/invoke-rc.d ]; then
+    if pathfind invoke-rc.d; then
       invoke-rc.d clamav-freshclam no-daemon || true
     else
       /etc/init.d/clamav-freshclam no-daemon || true
